#!/usr/bin/php
<?php

if (php_sapi_name() != "cli") {
    exit;
}

$data=fopen('https://www.nationalnanpa.com/nanp1/npa_report.csv', 'r');

$nanp = "<?php\n\n";
$nanp .= "# file autogenerated " . date("Y-m-d @ H:i:s") . "\n";
$nanp .= '$nanp=array();' . "\n\n";
$nanp .= "# NANP Auto Generated Entries\n";

while (($line = fgetcsv($data)) !== false) {
    if (isset($line[10]) && $line[10] == "Y") {
        $nanp .= '$nanp[]=' . $line[0] . ";\n";
    }
}
$nanp .="\n";

$myfile = fopen("/opt/configs/nanp.php", "w") or die("Unable to open file!");
fwrite($myfile, $nanp);
fclose($myfile);
